# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base for building the application
FROM node:18-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies (ignoring scripts to prevent running the prepare script)
RUN npm install --ignore-scripts

# Copy the rest of the application source code
COPY . .

# Build the application using TypeScript
RUN npm run build

# Use a smaller Node.js image for the final image
FROM node:18-slim AS release

# Set the working directory inside the container
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set environment variables for API key and custom API URL if needed
ENV FIRECRAWL_API_KEY=your-api-key
ENV FIRECRAWL_API_URL=https://firecrawl.your-domain.com

# Specify the command to run the application
ENTRYPOINT ["node", "dist/src/index.js"]
