FROM node:22-slim

WORKDIR /app

COPY package.json package-lock.json* ./


COPY tsconfig.json ./
COPY src ./src
RUN npm run build

ENV CLOUD_SERVICE=true
ENV PORT=3000

# Expose the port
EXPOSE 3000

# Run the server
CMD ["node", "dist/index.js"]